In [31]:
import numpy as np
b1=3
c1=3
a=np.random.randint(0,10,(b1,c1))
b2=3
c2=2
b=np.random.randint(0,10,(b2,c2))
print(a)
print(b)
if(c1==b2):
    arr=np.zeros((b1,c2))
    add=0
    for i in range(0, b1):
        for j in range(0, c2):
            for k in range(0, b2):
                add=add+(a[i][k]*b[k][j])
            arr[i][j]=add
            add=0
    print("manually")
    print(arr)
else:
    print("matrix multiplication not possible")

print("function")
arr1=np.matmul(a,b)
print(arr1)
            
                
                

[[1 0 5]
 [2 6 6]
 [0 2 4]]
[[4 9]
 [5 1]
 [4 8]]
manually
[[24. 49.]
 [62. 72.]
 [26. 34.]]
function
[[24 49]
 [62 72]
 [26 34]]
