In [12]:
import numpy as np
a=[]
a1=[]
print("for first matrices")
Row_size=int(input("enter rows = "))
Column_size=int(input("enter columns = "))
for i in range(0, Row_size):
    for j in range(0, Column_size):
        a.append(int(input("enter number rowwise  = ")))
    a1.append(a)
    a=[]
arr=np.array(a1)
print(arr)
a=[]
a1=[]
print("for second matrices")
Row_size1=int(input("enter rows = "))
Column_size1=int(input("enter columns = "))
for i in range(0, Row_size1):
    for j in range(0, Column_size1):
        a.append(int(input("enter number rowwise  = ")))
    a1.append(a)
    a=[]
arr1=np.array(a1)
print(arr1)
if(Column_size==Column_size1):
    r1=Row_size+Row_size1
    print(r1)
    az=np.zeros((r1,Column_size))
    for i in range(0, Row_size):
        for j in range(0, Column_size):
            az[i][j]=arr[i][j]
    num=i+1
    for i in range(num, r1):
        for j in range(0, Column_size1):
            az[i][j]=arr1[i-num][j]
    print(az)
else:
    print("invalid range")

for first matrices
enter rows = 3
enter columns = 4
enter number rowwise  = 1
enter number rowwise  = 2
enter number rowwise  = 3
enter number rowwise  = 4
enter number rowwise  = 3
enter number rowwise  = 4
enter number rowwise  = 5
enter number rowwise  = 6
enter number rowwise  = 4
enter number rowwise  = 5
enter number rowwise  = 6
enter number rowwise  = 7
[[1 2 3 4]
 [3 4 5 6]
 [4 5 6 7]]
for second matrices
enter rows = 2
enter columns = 4
enter number rowwise  = 1
enter number rowwise  = 2
enter number rowwise  = 3
enter number rowwise  = 4
enter number rowwise  = 2
enter number rowwise  = 3
enter number rowwise  = 4
enter number rowwise  = 5
[[1 2 3 4]
 [2 3 4 5]]
5
[[1. 2. 3. 4.]
 [3. 4. 5. 6.]
 [4. 5. 6. 7.]
 [1. 2. 3. 4.]
 [2. 3. 4. 5.]]
