In [1]:
import numpy as np
arr=np.array([[1,2,3],[2,3,4],[3,4,5]])
arr1=np.array([[3,4,5],[4,6,7]])
a=[]
a1=[]
for i in range(0, arr.shape[0]):
    for j in range(0, arr.shape[1]):
        a.append(arr[i][j])
    a1.append(a)
    a=[]
a=[]
for i in range(0, arr1.shape[0]):
    for j in range(0, arr1.shape[1]):
        a.append(arr1[i][j])
    a1.append(a)
    a=[]
arr2=np.array(a1)
print(arr2)
print(type(arr2))

[[1 2 3]
 [2 3 4]
 [3 4 5]
 [3 4 5]
 [4 6 7]]
<class 'numpy.ndarray'>


In [3]:
import numpy as np
arr=np.array([[1,2,3],[2,3,4],[3,4,5]])
arr1=np.array([[3,4,5],[4,6,7]])
a=[]
a1=[]
for i in range(arr.shape[0]):
    for j in range(arr.shape[1]):
        a.append(arr[i][j])
    a1.append(a)
    a=[]
a=[]
for i in range(0, arr1.shape[0]):
    for j in range(0, arr1.shape[1]):
        a.append(arr1[i][j])
    a1.append(a)
    a=[]
arr2=np.array(a1)
print(arr2)

[[1 2 3]
 [2 3 4]
 [3 4 5]
 [3 4 5]
 [4 6 7]]
